services:
  - type: web
    name: twxnbot
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install --no-cache-dir --prefer-binary -r requirements.txt
      python -m playwright install chromium --with-deps
    startCommand: python bot1.py
    plan: free
    autoDeploy: true
